@startuml
left to right direction
actor "Empleado" as em
actor "Administrador" as ad

rectangle "Empresa Pedidos"{
usecase "Introducir Pedido" as ip
usecase "Cancelar Pedido" as cp
usecase "Obtener Estado Pedido" as op
usecase "Borrar Pedido" as bop
usecase "Buscar Pedidos" as bup
usecase "Alta Cliente" as ac
usecase "Buscar Cliente" as bc
usecase "Nuevo producto" as np
usecase "Borrar Producto" as bpro
}
em--ip
em--cp
em--op
em--bop
em--bup
em--ac
em--bc
ad--np
ad--bpro


@enduml