@startuml

actor "Agente" as ag

  usecase "Enviar Solicitud de Crédito" as env
  usecase "Enviar Solicitud de Crédito Personal" as cp
  usecase "Enviar Solicitud de Crédito Empresarial" as ce

ag-->env
cp--|>env
ce--|>env
@enduml